### ISSUE TITLE
How to visualize raw point cloud with .bin file?

### ISSUE THREAD

**Issue by rann1018** [XLechter/PCAN#1]
Hi @XLechter 
Thanks a lot for your work!
When I download the datasets, I see there are many subsampled point clouds with .bin file.
How can I visualize these point clouds files?
Thanks for your attention.

**Comment by XLechter** [comment]
Hi @rann1018 ,
You first check the load_pc_file function in 'loading_pointclouds.py' to conver the .bin file to numpy array, then you can use open3d to visulize the point cloud.
